version: "2"

linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  dupl:
    threshold: 100

linters:
  disable-all: true
  enable:
    # Enabled by default
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional useful linters
    - bodyclose
    - dupl
    - gocyclo
    - gocritic
    - gosec
    - misspell
    - nakedret

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl

run:
  timeout: 5m
